// categories
export const SET_LOADING = 'SET_LOADING';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_SUBCATEGORIES = 'GET_SUBCATEGORIES';
export const GET_HOME_CATEGORIES = 'GET_HOME_CATEGORIES';
export const GET_HOME_SUBCATEGORIES = 'GET_HOME_SUBCATEGORIES';
export const GET_NAVBAR_CATEGORIES = 'GET_NAVBAR_CATEGORIES';
export const GET_CURRENT_SUBCATEGORIE = 'GET_CURRENT_SUBCATEGORIE';
// products
export const SET_LOADING_PRODUCTS = 'SET_LOADING_PRODUCTS';
export const GET_HOME_PRODUCTS = 'GET_HOME_PRODUCTS';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const COUNT_PRODUCTS = 'COUNT_PRODUCTS';
export const SET_SORTBY = 'SET_SORTBY';
export const PAGE_NUMBER = 'PAGE_NUMBER';
export const GET_PRODUCT_BRANDS = 'GET_PRODUCT_BRANDS';
export const SET_FILTER = 'SET_FILTER';
export const CURRENT_PRODUCT = 'CURRENT_PRODUCT';
export const CLEAR_PRODUCTS_DATA = 'CLEAR_PRODUCTS_DATA';
export const SET_SELECTED_PRODUCT = 'SET_SELECTED_PRODUCT';
export const SET_MODAL_OPENED = 'SET_MODAL_OPENED';

// brands
export const SET_LOADING_BRANDS = 'SET_LOADING_BRANDS';
export const GET_CURRENT_BRAND = 'GET_CURRENT_BRAND';
export const GET_BRANDS = 'GET_BRANDS';

//users
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const SET_LOADING_AUTH = 'SET_LOADING_AUTH';
// cart
export const CART_LOAD = 'CART_LOAD';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY';
export const DECREMENT_QUANTITY = 'DECREMENT_QUANTITY';
export const SET_LOADING_CART = 'SET_LOADING_CART';
export const CLEAR_CART = 'CLEAR_CART';

// lang
export const SET_LANG = 'SET_LANG';
